### ISSUE TITLE
Implement: affine_transform

### ISSUE THREAD

**Issue by stuartlynn** [kylebarron/geopolars#21]
This should take a GeoSeries, and a transformation matrix representing an [affine transform](https://en.wikipedia.org/wiki/Affine_transformation), and return the geometries with that affine transform applied.

Is this implemented in the Geo crate: I don't think so, but some simpler transforms are. 
GeoPandas equivalent: [affine transform](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoSeries.affine_transform.html)

**Comment by kylebarron** [comment]
Similar to #23 I think this is related to https://github.com/georust/geo/issues/728

**Comment by urschrei** [comment]
Just a heads-up that we're making some good progress on both general affine transform and scale & skew in Geo here: https://github.com/georust/geo/pull/866

**Comment by stuartlynn** [comment]
Amazing thanks!

**Comment by stuartlynn** [comment]
@urschrei if your interested, we just opened a PR to implement these as part of the GeoSeries #39 

Thanks for getting these merged in Geo
