### ISSUE TITLE
Implement: Scale

### ISSUE THREAD

**Issue by stuartlynn** [kylebarron/geopolars#23]
This should take a GeoSeries and scale  factors in each dimension (in units of the CRS) and an origin  and return a GeoSeries with geometries scaled by those amounts around that origin.

Origin can be 

```rust
enum Origin{
  Centroid, // The centroid of the object
  Center, // The center of the bounding box of the object,
  Point(Point), // A point to rotate around 
}
```

Is this implemented in the Geo crate: Don't think so. 
GeoPandas equivalent: [scale](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoSeries.scale.html)

Note once affine transform is defined we might be able to implement this by calculating the appropriate transform matrix and applying it.

**Comment by kylebarron** [comment]
Relevant `geo` issue: https://github.com/georust/geo/issues/728
