### ISSUE TITLE
Implement: Length

### ISSUE THREAD

**Issue by stuartlynn** [kylebarron/geopolars#30]
Given a GeoSeries, this should return the length of each of the geometries in the series in the units of the series CRS.
For MultiPolygons it should return the length of the exterior 

Geopandas equivalent: [length](https://geopandas.org/en/stable/docs/reference/api/geopandas.GeoSeries.length.html)
Implemented in Geo crate : Yes , it implements [geodesic length](https://docs.rs/geo/latest/geo/algorithm/geodesic_length/index.html) for lines, so we would need to first calculate the exterior of a geometry then use this function to calculate the length

**Comment by kylebarron** [comment]
If it's _in the units of the geometries' CRS_, then shouldn't it be the [euclidean length](https://docs.rs/geo/latest/geo/algorithm/euclidean_length/index.html) instead?

Geodesic length seems to be designed for lon/lat geometries but where the user wants precise lengths in meters.
