### ISSUE TITLE
Subclass from `polars.DataFrame` in Python

### ISSUE THREAD

**Issue by kylebarron** [kylebarron/geopolars#33]
Similarly to how `geopandas.GeoDataFrame` subclasses from `pandas.DataFrame`, I think it would be clean if `geopolars.GeoDataFrame` subclassed from `polars.DataFrame`. Then all the methods from polars are still available.

In https://github.com/kylebarron/geopolars/pull/4 I originally took a stab at this, but ran into a mess because when subclassing _from within Rust_, it appears that you need to additionally need to compile the library you're wrapping. We really don't want to compile polars' Python API.

Instead, we should explore doing this subclassing _from within Python_. I'm not 100% on how `py-polars` is set up, but it has both [Rust code](https://github.com/pola-rs/polars/tree/4e83b4012e06c84581ce9fe90d0b664cb4a054d4/py-polars/polars) _and_ [Python code](https://github.com/pola-rs/polars/tree/4e83b4012e06c84581ce9fe90d0b664cb4a054d4/py-polars/polars) within the `py-polars` directory. So it seems like pyo3/maturin have a way to distribute both rust code and python code together. (It looks like in the polars case, [`polars.polars` is the entrypoint to the rust bindings](https://github.com/pola-rs/polars/blob/4e83b4012e06c84581ce9fe90d0b664cb4a054d4/py-polars/polars/internals/frame.py#L59)).

When the subclassing happens from within Python, it also means that `polars` and `geopolars` could be installed separately and subclassed at runtime, and so we shouldn't have issues with version conflicts that could happen if both were compiled against different versions of polars.

**Comment by kylebarron** [comment]
There's a bit of docstring [here](https://github.com/pola-rs/polars/blob/4e83b4012e06c84581ce9fe90d0b664cb4a054d4/py-polars/polars/internals/frame.py#L107-L153) about how subclassing `DataFrame` in python works

**Comment by Oreilles** [comment]
Is it not possible to do that anymore ?

**Comment by kylebarron** [comment]
It's possible, but it has quite a lot of development overhead and doesn't allow using other polars features like its LazyFrame
